# Generated by Django 3.0.7 on 2020-06-07 08:43

from django.db import migrations, models
import imagefield.fields
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', imagefield.fields.ImageField(blank=True, height_field='image_height', upload_to='', verbose_name='image', width_field='image_width')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='description')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('token', models.CharField(blank=True, default=secrets.token_urlsafe, max_length=60)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
